board/urls.py
from django.urls import path
from .views import *

'''from .models import Photo'''

app_name = 'board'

urlpatterns = [
    path('', main, name='main'),
    path('space1', space1, name='space1')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('board.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

board/models.py
from django.db import models

# Create your models here.

board/views.py
from django.shortcuts import render

def main(request):
    return render(request,'board/main.html')

def space1(request):
    return render(request,'board/space1.html')

# Create your views here.

board/templates/board/(old)main.html
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="google" content="notranslate">
    <link rel="stylesheet" href="{% static "css/main.css" %}">
    <!--<script src="{% static "js/main.js" %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Odibee+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Anton" rel="stylesheet">

</head>

<div id="title" >
  <svg width="480" height="300">
    <pattern id="waveform" patternUnits="userSpaceOnUse" width="440" height="500" x="0" y="0">
      <image xlink:href="https://media.giphy.com/media/pp6KaeNp7cwuc/giphy.gif" width="500" height="300" />
    </pattern>

    <text text-anchor="middle" x="50%" y="20%" dy=".35em" class="text">
      We play Sports
    </text>

  </svg>
</div>

<div class="grid-layout">


    <div class="grid-space grid-space-1"><a href="{% url 'board:space1' %}">space 1</a></div>
    <div class="grid-space grid-space-2"><a href="{% url 'board:space1' %}">space 2</a></div>
    <div class="grid-space span-2 grid-space-3"><a href="{% url 'board:space1' %}">space 3</a></div>
    <div class="grid-space grid-space-4"><a href="{% url 'board:space1' %}">space 4</a></div>
    <div class="grid-space span-2 grid-space-5"><a href="{% url 'board:space1' %}">space 5</a></div>
    <div class="grid-space grid-space-6"><a href="{% url 'board:space1' %}">space 6</a></div>
    <div class="grid-space grid-space-7"><a href="{% url 'board:space1' %}">space 7</a></div>
    <div class="grid-space grid-space-8"><a href="{% url 'board:space1' %}">space 8</a></div>
    <div class="grid-space grid-space-9"><a href="{% url 'board:space1' %}">space 9</a></div>
    <div class="grid-space span-2 grid-space-10"><a href="{% url 'board:space1' %}">space 10</a></div>
    <div class="grid-space grid-space-11">space 11</div>
    <div class="grid-space grid-space-12">space 12</div>
    <div class="grid-space span-2 grid-space-13">space 13</div>
    <div class="grid-space grid-space-14">space 14</div>
    <div class="grid-space grid-space-15">space 15</div>
    <div class="grid-space grid-space-16">space 16</div>
    <div class="grid-space span-2 grid-space-17">space 17</div>
    <div class="grid-space grid-space-18">space 18</div>
    <div class="grid-space grid-space-19">space 19</div>
    <div class="grid-space grid-space-20">space 20</div>
    <div class="grid-space span-2 grid-space-21">space 21</div>
    <div class="grid-space grid-space-22">space 22</div>
    <div class="grid-space grid-space-23">space 23</div>
    <div class="grid-space grid-space-24">space 24</div>
    <div class="grid-space grid-space-25">space 25</div>
    <div class="grid-space span-2 grid-space-26">space 26</div>
    <div class="grid-space grid-space-27">space 27</div>
    <div class="grid-space grid-space-28">space 28</div>
    <div class="grid-space grid-space-29">space 29</div>
    <div class="grid-space grid-space-30">space 30</div>
    <div class="grid-space grid-space-31">space 31</div>
    <div class="grid-space grid-space-32">space 32</div>
    <div class="grid-space grid-space-33">space 33</div>
    <div class="grid-space grid-space-34">space 34</div>
    <div class="grid-space grid-space-35">space 35</div>
    <div class="grid-space grid-space-36">space 36</div>
    <div class="grid-space grid-space-37">space 37</div>
    <div class="grid-space grid-space-38">space 38</div>
    <div class="grid-space grid-space-39">space 39</div>
    <div class="grid-space span-2 grid-space-40">space 40</div>
    <div class="grid-space grid-space-41">space 41</div>
    <div class="grid-space grid-space-42">space 42</div>
    <div class="grid-space grid-space-43">space 43</div>
    <div class="grid-space grid-space-44">space 44</div>
    <div class="grid-space span-2 grid-space-45">space 45</div>
    <div class="grid-space grid-space-46">space 46</div>
    <div class="grid-space grid-space-47">space 47</div>
    <div class="grid-space grid-space-48">space 48</div>
    <div class="grid-space grid-space-49">space 49</div>
    <div class="grid-space span-3 grid-space-50">
      <p>Contact Adim : akasakaro.lee@gmail.com</p>
    </div>

</div>

board/templates/board/main.html
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="google" content="notranslate">
    <link rel="stylesheet" href="{% static "css/main.css" %}">
    <script src="{% static "js/main.js" %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Odibee+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Anton" rel="stylesheet">
    <script data-ad-client="ca-pub-5717096263298410" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script> <!-- 에드센스 -->


</head>

<div id="title" >
  <svg width="100%" height="150">
    <pattern id="waveform" patternUnits="userSpaceOnUse" width="400px" height="50px" x="0" y="0">
      <image xlink:href="https://media.giphy.com/media/pp6KaeNp7cwuc/giphy.gif">
    </pattern>

    <text text-anchor="middle" x="50%" y="50%" dy=".35em" class="text">
      We play Sports
    </text>

  </svg>

  <ul class="card-list">

	<li class="card">
		<a class="card-image" href="{% url 'board:space1' %}" data-image-full= "{% static "media/basketball.png" %}">
			<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/310408/psychopomp-100.jpg" alt="Psychopomp" />
		</a>
		<a class="card-description" href="{% url 'board:space1' %}" target="_blank">
			<h2>Basketball</h2>
		</a>
	</li>

    <!--
      	<li class="card">
		<a class="card-image" href="https://michellezauner.bandcamp.com/album/psychopomp-2" target="_blank" style="background-image: url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/310408/psychopomp-100.jpg);" data-image-full="https://s3-us-west-2.amazonaws.com/s.cdpn.io/310408/psychopomp-500.jpg">
			<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/310408/psychopomp-100.jpg" alt="Psychopomp" />
		</a>
		<a class="card-description" href="https://michellezauner.bandcamp.com/album/psychopomp-2" target="_blank">
			<h2>Psychopomp</h2>
			<p>Japanese Breakfast</p>
		</a>
	</li>
	-->

  <!-- 나중에 추가

	<li class="card">
		<a class="card-image" href="https://inlovewithaghost.bandcamp.com/album/lets-go" target="_blank" style="background-image: url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/310408/lets-go-100.jpg);" data-image-full="https://s3-us-west-2.amazonaws.com/s.cdpn.io/310408/lets-go-500.jpg">
			<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/310408/lets-go-100.jpg" alt="let's go" />
		</a>
		<a class="card-description" href="https://inlovewithaghost.bandcamp.com/album/lets-go" target="_blank">
			<h2>Comming soon</h2>
		</a>
	</li>

	<li class="card">
		<a class="card-image" href="https://vulfpeck.bandcamp.com/album/the-beautiful-game" target="_blank" style="background-image: url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/310408/beautiful-game-100.jpg);" data-image-full="https://s3-us-west-2.amazonaws.com/s.cdpn.io/310408/beautiful-game-500.jpg">
			<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/310408/beautiful-game-100.jpg" alt="The Beautiful Game" />
		</a>
		<a class="card-description" href="https://vulfpeck.bandcamp.com/album/the-beautiful-game" target="_blank">
			<h2>Comming soon</h2>
		</a>
	</li>

	<li class="card">
		<a class="card-image" href="https://convergecult.bandcamp.com/album/jane-doe" target="_blank" style="background-image: url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/310408/jane-doe-100.jpg);" data-image-full="https://s3-us-west-2.amazonaws.com/s.cdpn.io/310408/jane-doe-500.jpg">
			<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/310408/jane-doe-100.jpg" alt="Jane Doe" />
		</a>
		<a class="card-description" href="https://convergecult.bandcamp.com/album/jane-doe" target="_blank">
			<h2>Comming soon</h2>
		</a>
	</li>
	-->
</ul>

board/templates/board/space1.html
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="google" content="notranslate">
    <link rel="stylesheet" href="{% static "css/space.css" %}">
    <script src="{% static "js/space.js" %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Odibee+Sans&display=swap" rel="stylesheet">
    <script data-ad-client="ca-pub-5717096263298410" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script> <!--에드센스-->
</head>

<body>

  <div class="logo">We play sports</div>

        <div class="timer">
            <span id="min-decrease"onclick="minOneUp()"><i class="fas fa-angle-up"id="timectl1"></i></span>
            <div class="min"id="idMin">10</div>
            <span id="min-increase"onclick="minFiveUp()"><i class="fas fa-angle-double-up"id="timectl2"></i></span>
            :
            <span id="sec-decrease"onclick="secOneUp()"><i class="fas fa-angle-up"id="timectl3"></i></span>
            <div class="sec"id="idSec">00</div>
            <span id="sec-increase"onclick="secFiveUp()"><i class="fas fa-angle-double-up"id="timectl4"></i></span>


            <div class="start"><i onclick="timeStart()" class="fas fa-play" aria-hidden="false"id="idPlay"></i></div>
            <!--<i class="fas fa-pause"></i>-->
            <div class="reset"onclick="timeReset()"><i class="fas fa-redo"></i></div>
        </div>
         <div class="set">
             <a href="#"><i class="fas fa-cog"></i></a> <!--<i class="fas fa-tv"></i>-->
             <a href="#"><i class="fas fa-power-off"onclick="winOff()"></i></a>
            <!--<div class = "setting"> setting </div>
            <div class = "power"> Power </div>-->
         </div>
    </div>

    <div class="main-content">
        <div class="homebar">
           <div class="hometeambar">
            <div class="hometeamcolor" id="idhometeamcolor" onclick="colorChange()">Team color</div>
            <div class="hometeamname"  id="idhometeamname" onclick="nameChange()">Team name</div>
          </div>
          <div class="homepoint" id="idhomepoint" onclick="OneUpdScore()">00</div>
          <div class="point">
            <div class="point3" onclick="ThreeUpdScore()">+3</div>
            <div class="point2" onclick="TwoUpdScore()">+2</div>
            <div class="point-1" onclick="DownScore()">-1</div>
          </div>
        </div>
        <div class="setbar">
            <a><i class="fas fa-sync" id="sync" onclick="sync()"></i></a>
            <a><i class="fas fa-exchange-alt" id="exchange" onclick="exchange()"></i></a>
        </div>
        <div class="awaybar">
           <div class="awayteambar">
            <div class="awayteamcolor" id="idawayteamcolor" onclick="awaycolorChange()">Team color</div>
            <div class="awayteamname" id="idawayteamname" onclick="awaynameChange()">Team name</div>
          </div>
          <div class="awaypoint" id="idawaypoint" onclick="AwayOneUpdScore()">
            00
          </div>
          <div class="point">
            <div class="point3" onclick="AwayThreeUpdScore()">+3</div>
            <div class="point2" onclick="AwayTwoUpdScore()">+2</div>
            <div class="point-1" onclick="DownAwayScore()">-1</div>
          </div>
        </div>

        <div class="sidebar">
          <div class="icon">
            <a href="#"><i class="fas fa-volume-up"></i></a> <!-- <a href="#"><i class="fas fa-volume-mute"></i></a> -->
          </div>
          <div class="whatsound">
            <div class="property" onclick="PlaySoundTime()">Time</div>

            <div class="property" onclick="PlaySoundScore()">Score</div>

            <div class="property" onclick="PlaySoundFoul()">Foul</div>
            <audio id="audioFoul" src="{% static "media/faul.m4a" %}"> </audio>
            <div class="property" onclick="PlaySoundStart()">Start/End</div>
            <audio id="audioStart" src="{% static "media/end.m4a" %}"></audio>
          </div>
        </div>
    </div>
<script>

var txtInputHp = document.getElementById("idhomepoint");
var txtInputAp = document.getElementById("idawaypoint");
var txtInputMin = document.getElementById("idMin");
var txtInputSec = document.getElementById("idSec");



function PlaySoundTime() {
  speechTime = new SpeechSynthesisUtterance(txtInputMin.innerHTML + "minutes"  + txtInputSec.innerHTML + "second");
  /*speechTime.lang = "kr-KO"
  speechTime.Voice = "Alice" */
  console.log(speechTime);
  /*speechTime.voice = speechSynthesis.getVoices()[parseInt(voice.value)];*/
  speechSynthesis.speak(speechTime);
}

function PlaySoundScore() {
  speechScore = new SpeechSynthesisUtterance(txtInputHp.innerHTML + " to "  + txtInputAp.innerHTML);
  console.log(speechScore);
  /*speechScore.voice = speechSynthesis.getVoices()[parseInt(voice.value)];*/
  speechSynthesis.speak(speechScore);
}
</script>

</body>


    <div class="footer">

    </div>

</html>